/*
 * variable.c
 *
 *  Created on: 23 abr 2026
 *      Author: tomyl
 */

#ifndef SRC_VARIABLE_C_
#define SRC_VARIABLE_C_

/* Auto-generated by FSM Grapher */
#include <stdint.h>
#include "variable.h"


/* Process event and execute actions */
static estado_t fsm_alarma(evento_t event, var_t* v) {
    estado_t next = v->estado;
    switch (v->estado) {
        case VAR_NORMAL:
            if (event == VAR_VAL_EVT && (v->valor > v->umbral_alto)){
                next = VAR_HI;
                break;
            }
            if (event == VAR_VAL_EVT && (v->valor < v->umbral_bajo)) {
                next = VAR_LO;
                break;
            }
            break;
        case VAR_LO:
            if (event == VAR_VAL_EVT && (v->valor > v->umbral_alto)) {
                next = VAR_HI;
                break;
            }
            if (event == VAR_VAL_EVT && (v->valor >= v->umbral_bajo) && (v->valor <= v->umbral_alto)) {
                next = VAR_WAITING_ACK;
                break;
            }
            break;
        case VAR_HI:
            if (event == VAR_VAL_EVT && (v->valor < v->umbral_bajo)) {
                next = VAR_LO;
                break;
            }
            if (event == VAR_VAL_EVT && (v->valor >= v->umbral_bajo) && (v->valor <= v->umbral_alto)) {
                next = VAR_WAITING_ACK;
                break;
            }
            break;
        case VAR_WAITING_ACK:
            if (event == VAR_ACK_EVT) {
                next = VAR_NORMAL;
                break;
            }
            if (event == VAR_VAL_EVT && (v->valor < v->umbral_bajo)) {
                next = VAR_LO;
                break;
            }
            if (event == VAR_VAL_EVT && (v->valor > v->umbral_alto)) {
                next = VAR_HI;
                break;
            }
            break;
        default: break;
    }

    if (next != v->estado) {
    }
    return next;
}

/* Initialize FSM */
static estado_t iniciar_fsm(var_t* v) {
     estado_t initial;
     if ((v->valor > v->umbral_alto) && (v->valor >= v->umbral_bajo)){
    	 initial = VAR_HI;
     }
     else if((v->valor < v->umbral_bajo) && (v->valor <= v->umbral_alto)){
    	 initial = VAR_LO;
     }
     else{
    	 initial = VAR_NORMAL;
     }
    return initial;
}


 void var_init(var_t *v, float val_ini, float umbral_hi_ini, float umbral_lo_ini){
	 v->umbral_alto = umbral_hi_ini;
	 v->umbral_bajo = umbral_lo_ini;
	 v->valor = val_ini;
	 v->estado = iniciar_fsm(v);
 }

 void var_set_val(var_t* v, float new_val){
	 v->valor = new_val;
	 v->estado = fsm_alarma(VAR_VAL_EVT, v);
 }

 void var_ack_alarm(var_t* v){
	 v->estado = fsm_alarma(VAR_ACK_EVT, v);
 }

 estado_t var_get_state(var_t* v){
	 return v->estado;
 }

#endif /* SRC_VARIABLE_C_ */
